name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      ## yarn install
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      ## yarn eslint
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: eslint
      ## run tests -- works better than yarn test?
      - run: npm test
      ## yarn test -- seems to not run with right node version
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test
