name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      ## yarn install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      ## yarn eslint
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint
      ## yarn test
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
